// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vWiDw7x8zzs23HCiWDEAsq1hVbYfK_4',
    appId: '1:595920904804:web:0bb5151607e13bc3e9f571',
    messagingSenderId: '595920904804',
    projectId: 'my-flutter-project-dece5',
    authDomain: 'my-flutter-project-dece5.firebaseapp.com',
    storageBucket: 'my-flutter-project-dece5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmqGZliEBk3PSgH9Yjly7JUYesGSot_Mk',
    appId: '1:595920904804:android:4c015e79e814c083e9f571',
    messagingSenderId: '595920904804',
    projectId: 'my-flutter-project-dece5',
    storageBucket: 'my-flutter-project-dece5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCnp696_KXtnc0T65DhsgI_y0e2OYQKQ',
    appId: '1:595920904804:ios:add6a8b56f7b4aeee9f571',
    messagingSenderId: '595920904804',
    projectId: 'my-flutter-project-dece5',
    storageBucket: 'my-flutter-project-dece5.firebasestorage.app',
    androidClientId: '595920904804-0nrt6pl89d6b5pinjqg1sqsidfm655h4.apps.googleusercontent.com',
    iosClientId: '595920904804-kc6jirijo6e6nl2hnvovetdmtppl6n8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.pendakian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJCnp696_KXtnc0T65DhsgI_y0e2OYQKQ',
    appId: '1:595920904804:ios:add6a8b56f7b4aeee9f571',
    messagingSenderId: '595920904804',
    projectId: 'my-flutter-project-dece5',
    storageBucket: 'my-flutter-project-dece5.firebasestorage.app',
    androidClientId: '595920904804-0nrt6pl89d6b5pinjqg1sqsidfm655h4.apps.googleusercontent.com',
    iosClientId: '595920904804-kc6jirijo6e6nl2hnvovetdmtppl6n8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.pendakian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBveKYvgm8Gcb70WOl9kMKd9tmGyDMdM60',
    appId: '1:595920904804:web:51de794e10a74770e9f571',
    messagingSenderId: '595920904804',
    projectId: 'my-flutter-project-dece5',
    authDomain: 'my-flutter-project-dece5.firebaseapp.com',
    storageBucket: 'my-flutter-project-dece5.firebasestorage.app',
  );
}
